# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: billing.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class NEM2AMeterType(betterproto.Enum):
    NEM2A_METER_TYPE_UNSPECIFIED = 0
    GENERATION_METER = 1
    BENEFIT_METER = 2


@dataclass
class EnergyDate(betterproto.Message):
    value: str = betterproto.string_field(1)


@dataclass
class EnergyMetric(betterproto.Message):
    # Sometimes each metric comes from multiple values summed up. This can happen
    # when the rates change half way through the month (due to summer/winter
    # transitions or rate hikes)
    subcomponent_values: List[float] = betterproto.double_field(1)


@dataclass
class EnergyMetricTOU(betterproto.Message):
    """
    Some energy metrics are time-of-use (TOU) based, meaning they have
    different values for peak and off-peak times.
    """

    peak: "EnergyMetric" = betterproto.message_field(1)
    off_peak: "EnergyMetric" = betterproto.message_field(2)
    total: "EnergyMetric" = betterproto.message_field(3)


@dataclass
class MeterBillingMonth(betterproto.Message):
    """
    Represents a monthly bill for a single meter within the NEM2A system.
    """

    # The type of meter, either GenerationMeter or BenefitMeter
    nem2a_meter_type: "NEM2AMeterType" = betterproto.enum_field(1)
    # key dates
    billing_date: "EnergyDate" = betterproto.message_field(2)
    service_end_date: "EnergyDate" = betterproto.message_field(3)
    # Meter values (kWh) are always mapped to time of use.
    energy_export_meter_channel_2: "EnergyMetricTOU" = betterproto.message_field(4)
    energy_import_meter_channel_1: "EnergyMetricTOU" = betterproto.message_field(5)
    allocated_export_energy_credits: "EnergyMetricTOU" = betterproto.message_field(6)
    net_energy_usage_after_credits: "EnergyMetricTOU" = betterproto.message_field(7)
    # PCE values
    pce_energy_cost: "EnergyMetricTOU" = betterproto.message_field(8)
    pce_net_generation_bonus: "EnergyMetric" = betterproto.message_field(9)
    pce_energy_commission_surcharge: "EnergyMetric" = betterproto.message_field(10)
    pce_total_energy_charges: "EnergyMetric" = betterproto.message_field(11)
    pce_nem_credit: "EnergyMetric" = betterproto.message_field(12)
    pce_generation_charges_due_cash: "EnergyMetric" = betterproto.message_field(13)
    # PG&E
    pge_res_energy_charges: "EnergyMetric" = betterproto.message_field(14)
    pge_baseline_credit: "EnergyMetric" = betterproto.message_field(15)
    pge_da_cca_charges: "EnergyMetric" = betterproto.message_field(16)
    pge_total_energy_charges: "EnergyMetric" = betterproto.message_field(17)
    pge_nem_billing: "EnergyMetric" = betterproto.message_field(18)
    pge_minimum_delivery_charge: "EnergyMetric" = betterproto.message_field(19)
    pge_nem_true_up_adjustment: "EnergyMetric" = betterproto.message_field(20)
    pge_electric_delivery_charges: "EnergyMetric" = betterproto.message_field(21)
    # Totals
    california_climate_credit: "EnergyMetric" = betterproto.message_field(22)
    total_bill_in_mail: "EnergyMetric" = betterproto.message_field(23)


@dataclass
class MonthLabel(betterproto.Message):
    month_name: str = betterproto.string_field(1)
    year: int = betterproto.int32_field(2)


@dataclass
class NEM2AAggregationBillingMonth(betterproto.Message):
    """
    Represents a monthly bill for a single meter within the NEM2A system.
    """

    year: int = betterproto.int32_field(1)
    month: int = betterproto.int32_field(2)
    month_label: "MonthLabel" = betterproto.message_field(3)
    main: "MeterBillingMonth" = betterproto.message_field(4)
    adu: "MeterBillingMonth" = betterproto.message_field(5)


@dataclass
class BillingYear(betterproto.Message):
    """
    Represents a billing year, which consists of multiple billing months.
    """

    start_month: int = betterproto.int32_field(1)
    start_year: int = betterproto.int32_field(2)
    num_months: int = betterproto.int32_field(3)
    months: List["MonthLabel"] = betterproto.message_field(4)
    billing_months: List["NEM2AAggregationBillingMonth"] = betterproto.message_field(5)
