# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tariff.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class Season(betterproto.Enum):
    """Season for TOU rates (kept for potential future use)"""

    SEASON_UNSPECIFIED = 0
    SUMMER = 1
    WINTER = 2


@dataclass
class OptionalDouble(betterproto.Message):
    """
    Wrapper for optional double values (for nullable rate values) Follows the
    pattern of OptionalInt32 in metadata.proto
    """

    value: float = betterproto.double_field(1)


@dataclass
class SeasonalTOURates(betterproto.Message):
    """TOU rates for a specific season"""

    peak: "OptionalDouble" = betterproto.message_field(1)
    off_peak: "OptionalDouble" = betterproto.message_field(2)


@dataclass
class TOURates(betterproto.Message):
    """Complete TOU rate structure for both seasons"""

    summer: "SeasonalTOURates" = betterproto.message_field(1)
    winter: "SeasonalTOURates" = betterproto.message_field(2)


@dataclass
class SeasonalBaselineQuantities(betterproto.Message):
    """
    Seasonal baseline allowance for Territory T individually metered customers
    only
    """

    territory_t_individually_metered: float = betterproto.double_field(1)


@dataclass
class BaselineQuantities(betterproto.Message):
    """
    Complete baseline quantities structure for Territory T individually metered
    customers
    """

    winter: "SeasonalBaselineQuantities" = betterproto.message_field(1)
    summer: "SeasonalBaselineQuantities" = betterproto.message_field(2)
    note: str = betterproto.string_field(3)


@dataclass
class TOUPeriodDefinitions(betterproto.Message):
    """
    Human-readable TOU period information These are descriptive strings that
    explain when peak/off-peak periods occur
    """

    peak_hours: str = betterproto.string_field(1)
    peak_days: str = betterproto.string_field(2)
    off_peak_hours: str = betterproto.string_field(3)
    summer_season: str = betterproto.string_field(4)
    winter_season: str = betterproto.string_field(5)


@dataclass
class TariffPeriod(betterproto.Message):
    """
    Single tariff rate period with effective dates Represents one Excel file's
    worth of tariff data
    """

    source_file: str = betterproto.string_field(1)
    effective_start: str = betterproto.string_field(2)
    effective_end: str = betterproto.string_field(3)
    # Fixed charges (per day)
    delivery_minimum: "OptionalDouble" = betterproto.message_field(4)
    total_meter_charge: "OptionalDouble" = betterproto.message_field(5)
    # Credits (negative values)
    baseline_credit: "OptionalDouble" = betterproto.message_field(6)
    ca_climate_credit: "OptionalDouble" = betterproto.message_field(7)
    # TOU rates
    tou_rates: "TOURates" = betterproto.message_field(8)
    # Baseline quantities by territory
    baseline_quantities: "BaselineQuantities" = betterproto.message_field(9)
    # TOU period definitions
    tou_periods: "TOUPeriodDefinitions" = betterproto.message_field(10)
    # Optional note for special cases
    note: str = betterproto.string_field(11)


@dataclass
class TariffSchedule(betterproto.Message):
    """
    Collection of all tariff periods for E-TOU-C tariff (Territory T only)
    """

    tariff_name: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    periods: List["TariffPeriod"] = betterproto.message_field(3)
